Repository upskill-team/Front-End-DSW, pull requests merged in 2025-08, with the labels that each got.

#11 ref: update readme with git flow info
  README.md
Labels: documentation, needs-review

#38 chore(workflow): Add automated issue templates
  .github/ISSUE_TEMPLATE/nueva-funcionalidad.md
  .github/ISSUE_TEMPLATE/reporte-bug.md
Labels: chore

#40 chore: Changed the Feature and Bug templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/nueva-funcionalidad.md
  .github/ISSUE_TEMPLATE/reporte-bug.md
Labels: needs-review, chore

#46 Fix/ci workflow and triggers
  .github/workflows/auto-pr.yml
  package.json
  pnpm-lock.yaml
Labels: needs-review, bugfix, chore

#49 fix: Update issue templates
  .github/ISSUE_TEMPLATE/nueva-funcionalidad.md
Labels: bugfix

#58 Feature/Implementation of the professor dashboard
  package.json
  src/components/layouts/NavBar.tsx
  src/pages/Professor/ProfessorAnalyticsPage.tsx
  src/pages/Professor/ProfessorCoursesPage.tsx
  src/pages/Professor/ProfessorDashboard.tsx
  src/pages/Professor/ProfessorStudentsPage.tsx
  src/router/AppRouter.tsx
Labels: feature

#60 feat(admin): Implementar gestión de Tipos de Curso desde el panel de admin
  src/api/services/courseType.service.ts
  src/components/landing/Footer.tsx
  src/components/layouts/NavBar.tsx
  src/pages/Admin/CourseTypesPage.tsx
  src/pages/Admin/CoursesPage.tsx
  src/pages/Admin/ProfessorRequestsPage.tsx
  src/pages/Admin/UsersPage.tsx
  src/router/AppRouter.tsx
Labels: needs-review, feature

#69 fix(admin): Mejorar la responsividad y consistencia visual del Panel de Admin y Layouts
  index.html
  src/components/common/Footer.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/NavBar.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/DocumentViewer.tsx
  src/pages/Admin/ProfessorAppealsPage.tsx
  src/pages/Admin/ProfessorRequestsPage.tsx
  src/pages/LandingPage.tsx
  src/router/AppRouter.tsx
Labels: needs-review, bugfix, refactor

#75 refactor: Migrar gestión de formularios a React Hook Form y Valibot
  package.json
  pnpm-lock.yaml
  src/components/ui/Input.tsx
  src/components/ui/TextArea.tsx
  src/pages/Admin/CourseTypesPage.tsx
  src/pages/Auth/ForgotPasswordPage.tsx
  src/pages/Auth/LoginPage.tsx
  src/pages/Auth/RegisterPage.tsx
  src/pages/Auth/ResetPasswordPage.tsx
  src/pages/Professor/ProfessorAppeal.tsx
Labels: needs-review, refactor
