Repository upskill-team/Front-End-DSW, pull requests merged in 2025-09, with the labels that each got.

#91 Chore: Estandarizar Estructura de Carpetas de UI
  src/components/common/NavBar.tsx
  src/components/layouts/MainLayout.tsx
  src/pages/LandingPage.tsx
Labels: needs-review, refactor, chore

#92 Feat: Crear y Aplicar Utilidad 'cn' para Composición de Clases
  src/components/ui/Button.tsx
  src/lib/utils.ts
Labels: needs-review, feature, refactor

#100 feat: Implementacion de API service, hooks y tipos para la gestión de Cursos
  src/api/services/course.service.ts
  src/hooks/useCourses.ts
  src/pages/Professor/ProfessorCoursesPage.tsx
  src/types/entities.ts
Labels: needs-review, feature

#101 feat: Desarrolla el flujo de creación y la página de edición de Cursos
  src/api/services/course.service.ts
  src/components/ui/Card.tsx
  src/components/ui/Dialog.tsx
  src/components/ui/Switch.tsx
  src/hooks/useCourses.ts
  src/pages/Admin/CourseTypesPage.tsx
  src/pages/Professor/ProfessorCourseCreation.tsx
  src/pages/Professor/ProfessorCourseEdition.tsx
  src/pages/Professor/ProfessorCoursesPage.tsx
  src/pages/Professor/ProfessorDashboard.tsx
  src/router/AppRouter.tsx
  src/types/entities.ts
Labels: needs-review, feature

#121 feat: Implementacion de vista de perfil de usuario y edición de datos
  src/api/services/user.service.ts
  src/components/common/NavBar.tsx
  src/components/ui/Avatar.tsx
  src/components/ui/DropdownMenu.tsx
  src/components/ui/ProfileField.tsx
  src/components/ui/RoleBadge.tsx
  src/components/ui/Tabs.tsx
  src/contexts/AuthContext.tsx
  src/contexts/AuthProvider.tsx
  src/hooks/useUserMutations.ts
  src/pages/User/ProfilePage.tsx
  src/router/AppRouter.tsx
  src/types/entities.ts
Labels: needs-review, feature
